"""Catálogo de patrones agénticos extraídos del ecosistema AGViewer.

Cada patrón documenta un mecanismo de coordinación multi-agente que se ha
validado en producción. Los patrones son agnósticos al dominio: aplican a
cualquier proyecto que quiera coordinar agentes (locks, tareas, comunicación,
auditoría, etc.).

El contenido es bilingüe (EN/ES) — la clave `en` se usa como default y `es`
está disponible para proyectos primariamente en español.
"""

from typing import Optional

from . import storage

# 15 patrones validados en el ecosistema AGViewer.
PATTERNS: list[dict] = [
    {
        "name": "lock_system",
        "domain": "coordination",
        "description": "File-based multi-agent locking with TTL, heartbeat and atomic acquisition.",
        "when_to_use": "Multiple agents (or sessions) may write the same resource concurrently.",
        "implementation_guide": [
            "Lock files in `.locks/{sha256(resource)}.lock` with atomic O_CREAT|O_EXCL creation",
            "Content: `agent_id | role | acquired_at | ttl_minutes | heartbeat_at`",
            "Acquire: create atomically; reclaim if heartbeat expired; renew if same agent",
            "Release only by owner; force-unlock restricted to admin/supervisor roles",
            "Write every operation to the session log (audit trail)",
        ],
        "related": ["access_control", "heartbeat_daemon", "session_audit"],
        "en": "Prevents race conditions without a central server. Lock expiry handles crashed agents automatically.",
        "es": "Previene race conditions sin servidor central. La expiración por TTL maneja agentes caídos automáticamente.",
    },
    {
        "name": "task_system",
        "domain": "coordination",
        "description": "Checkbox-based task queue with inline fields, single canonical source, auto-generated kanban.",
        "when_to_use": "Any project where tasks must be claimable, prioritized and traced by agents.",
        "implementation_guide": [
            "Canonical file `AGENT_TASKS.md` with `- [ ] T{n}: desc [field:: value]` lines",
            "Fields: priority, status (backlog/doing/review/done/blocked), type, repo, depends, due, agent",
            "One canonical source; kanban boards are derived views regenerated by a script",
            "Claim via git push rejection (race-condition-free distributed claiming)",
            "Never edit derived boards manually — edit canonical, then re-sync",
        ],
        "related": ["kanban_sync", "distributed_coordination", "access_control"],
        "en": "Bridges human-readable markdown with machine-parseable structured data.",
        "es": "Conecta markdown legible por humanos con datos estructurados parseables por máquinas.",
    },
    {
        "name": "agent_lifecycle",
        "domain": "identity",
        "description": "Register → Heartbeat → Work → Close session lifecycle with stale-sweep recovery.",
        "when_to_use": "Every agent that operates on a project must have traceable identity and sessions.",
        "implementation_guide": [
            "Register in `AGENT_REGISTRY.md`: agent_id, role, session_token, started, heartbeat, status, task",
            "Roles: explorer (read-only), worker (write under lock), supervisor (assign), admin (full)",
            "Heartbeat every 5 min to keep session active; sessions expire without heartbeat",
            "Close session: release all locks, mark inactive, log summary",
            "Stale sweep: any agent may close zombie sessions (heartbeat > TTL)",
        ],
        "related": ["session_audit", "zombie_cleanup", "access_control"],
        "en": "Unregistered agents default to read-only explorer — identity is the baseline of trust.",
        "es": "Los agentes no registrados son solo lectura (explorer) — la identidad es la base de la confianza.",
    },
    {
        "name": "comms_system",
        "domain": "coordination",
        "description": "Append-only inter-agent message board with labels (handoff, blocked, question, notice, escalation).",
        "when_to_use": "Agents need to coordinate cross-task or escalate blockers to other agents or humans.",
        "implementation_guide": [
            "`AGENT_COMMS.md` table: `| timestamp | from | to | label | message |`",
            "Labels standardize intent: handoff, blocked, question, notice, escalation",
            "Append-only — never edit existing messages; archive after resolution",
            "Check inbox at session start (filter by your agent_id)",
            "Optional threaded JSON version for structured consumers",
        ],
        "related": ["agent_lifecycle", "distributed_coordination"],
        "en": "Simple durable messaging without a broker — the git history is the transport.",
        "es": "Mensajería simple y durable sin broker — el historial de git es el transporte.",
    },
    {
        "name": "session_audit",
        "domain": "observability",
        "description": "Append-only JSONL audit log of every agent action (register, lock, unlock, heartbeat, close).",
        "when_to_use": "Any system needing accountability, forensics and post-hoc diagnosis.",
        "implementation_guide": [
            "`AGENT_SESSION_LOG.md` with one JSON object per line (JSONL)",
            "Schema: timestamp, agent_id, role, action, resource, status, details",
            "Append with each lifecycle/lock operation (no overwrite, no edit)",
            "Atomic append is enough — JSONL tolerates concurrent appends",
            "Reference task IDs (T-IDs) in details for traceability",
        ],
        "related": ["agent_lifecycle", "lock_system"],
        "en": "The audit log makes agent behavior debuggable and learning possible.",
        "es": "El log de auditoría hace el comportamiento del agente debuggable y el aprendizaje posible.",
    },
    {
        "name": "access_control",
        "domain": "security",
        "description": "Role × resource permission matrix that gates writes and escalations.",
        "when_to_use": "Agents with different trust levels share the same workspace.",
        "implementation_guide": [
            "Roles: explorer, worker, supervisor, admin with increasing privilege",
            "Matrix per resource: READ, WRITE, WRITE (under lock), APPEND, FULL",
            "Write under lock is the default for shared mutable files",
            "Force-unlock and role assignment restricted to supervisor/admin",
            "Define penalties for violations (warning, downgrade, suspension)",
        ],
        "related": ["lock_system", "agent_lifecycle"],
        "en": "Prevents a single over-privileged agent from corrupting shared state.",
        "es": "Evita que un agente con exceso de permisos corrompa el estado compartido.",
    },
    {
        "name": "distributed_coordination",
        "domain": "coordination",
        "description": "Git as the coordination bus: push rejection resolves task-claiming and lock races across machines.",
        "when_to_use": "Agents run on different machines/clones and must share one task queue.",
        "implementation_guide": [
            "git pull --rebase before claiming; edit canonical task; git push",
            "If push rejected → another agent claimed it → pull --rebase → pick another task",
            "Git-based locks via registry column `[lock:: resource]` for multi-machine writes",
            "Resolution of conflicts is deterministic (first-push wins)",
        ],
        "related": ["task_system", "lock_system"],
        "en": "No central coordinator needed — git history is the source of truth and arbitration.",
        "es": "No se necesita coordinador central — el historial de git es la fuente de verdad y arbitraje.",
    },
    {
        "name": "kanban_sync",
        "domain": "workflow",
        "description": "Canonical task file + auto-generated kanban boards from one source of truth.",
        "when_to_use": "Visual boards should reflect task state without manual duplication.",
        "implementation_guide": [
            "Parse canonical tasks with regex `- \\[([ xX])\\] ...` + `[field:: value]` extraction",
            "Generate tasks board grouped by status; roadmap grouped by quarter from `[due::]`",
            "Write boards as derived files with 'DO NOT EDIT' frontmatter",
            "Re-run the sync script after any canonical edit (or auto via CI)",
        ],
        "related": ["task_system"],
        "en": "Automation beats discipline — the board can never drift from the canonical file.",
        "es": "La automatización supera la disciplina — el board nunca diverge del archivo canónico.",
    },
    {
        "name": "heartbeat_daemon",
        "domain": "observability",
        "description": "Background process that refreshes an agent's heartbeat every N minutes.",
        "when_to_use": "Long-running agent sessions must not expire their locks or session.",
        "implementation_guide": [
            "Fork a background process that calls lock heartbeat every 300s",
            "Track PIDs in a temp dir for start/stop/status control",
            "Trap SIGTERM/SIGINT to clean up on shutdown",
            "Heartbeat keeps both session registry and locks alive",
        ],
        "related": ["lock_system", "agent_lifecycle"],
        "en": "Keeps long sessions alive without manual heartbeat discipline.",
        "es": "Mantiene sesiones largas vivas sin requerir disciplina manual de heartbeat.",
    },
    {
        "name": "zombie_cleanup",
        "domain": "observability",
        "description": "Scheduled job that marks stale sessions as zombies and force-unlocks their resources.",
        "when_to_use": "Crashed agents leave stale heartbeats and held locks that block others.",
        "implementation_guide": [
            "Scan registry for active agents with heartbeat older than TTL → mark zombie",
            "Force-unlock all locks owned by zombies",
            "Remove expired locks (heartbeat > TTL)",
            "Run as cron every 15 minutes or on session start (stale_sweep)",
        ],
        "related": ["agent_lifecycle", "lock_system", "heartbeat_daemon"],
        "en": "Self-healing coordination — the system recovers from dead agents automatically.",
        "es": "Coordinación auto-reparable — el sistema se recupera de agentes muertos automáticamente.",
    },
    {
        "name": "mcp_tool_design",
        "domain": "interface",
        "description": "Expose agentic infrastructure to AI agents via MCP (Model Context Protocol) tools.",
        "when_to_use": "Any agent (OpenCode, Claude Code, Cursor) must interact with the workspace through tools.",
        "implementation_guide": [
            "One MCP server exposing tools over stdio",
            "Define tools with name + description + JSON schema (required/optional args)",
            "Inject system context (health, warnings, anomalies) into every response",
            "Keep agent-lifecycle + vault tools generic; domain tools pluggable",
            "Run handlers in executor threads to avoid blocking the event loop",
        ],
        "related": ["domain_tool_pattern", "vault_structure"],
        "en": "MCP is the lingua franca for AI agents — one protocol, many clients.",
        "es": "MCP es la lingua franca para agentes de IA — un protocolo, muchos clientes.",
    },
    {
        "name": "domain_tool_pattern",
        "domain": "interface",
        "description": "Separate domain-specific tools into a pluggable module registered with the MCP server.",
        "when_to_use": "Each project has unique queries (health, deploy, pipeline) that should not pollute the core.",
        "implementation_guide": [
            "Create `{project}_tools.py` with a `register_tools(server)` function",
            "Each tool: descriptive docstring, typed args, structured return",
            "Reference task IDs and document customizations with CUSTOMIZE:/TODO: comments",
            "Keep the core server lean; load domain tools via a single import",
        ],
        "related": ["mcp_tool_design"],
        "en": "Plugins keep the core portable and the domain-specific logic isolated.",
        "es": "Los plugins mantienen el core portable y la lógica específica de dominio aislada.",
    },
    {
        "name": "vault_structure",
        "domain": "knowledge",
        "description": "Obsidian vault with wiki links, tags, MOCs and Dataview dashboards for human+agent navigation.",
        "when_to_use": "Documentation must be navigable by humans in Obsidian and queryable by agents.",
        "implementation_guide": [
            "`00_Global/Home.md` as hub; MOC-*.md as maps of content",
            "Tag taxonomy (#rules, #agents, #iac, #state) for graph queries",
            "Dashboards with Dataview queries over frontmatter/inline fields",
            "Build a wiki-link graph tool for backlinks, by_tag, orphans, clusters",
            "Cross-link every file back to Home",
        ],
        "related": ["mcp_tool_design"],
        "en": "A structured vault is both human documentation and agent-queryable knowledge graph.",
        "es": "Un vault estructurado es a la vez documentación humana y grafo de conocimiento consultable por agentes.",
    },
    {
        "name": "protocol_writing",
        "domain": "knowledge",
        "description": "Encode operating rules as markdown protocols with deliberation frameworks and risk tiers.",
        "when_to_use": "Agent behavior must be consistent, safe and auditable across sessions.",
        "implementation_guide": [
            "AGENT_PROTOCOL.md: deliberation framework (classify→analyze→plan→validate→execute→verify)",
            "Risk tiers: READ/DOCS/CODE/INFRA with escalating lifecycle requirements",
            "Evidence discipline: confidence levels (ALTA/MEDIA/BAJA), cross-verify 2 sources",
            "Session bootstrap: check zombie sessions, register, lock, verify against live data",
            "Learning reflex: every mistake becomes a new rule, trap or skill",
        ],
        "related": ["agent_lifecycle", "trap_documentation"],
        "en": "Protocols make agent behavior reproducible and continuously improvable.",
        "es": "Los protocolos hacen el comportamiento del agente reproducible y mejorable continuamente.",
    },
    {
        "name": "trap_documentation",
        "domain": "knowledge",
        "description": "Tribal knowledge file capturing recurring technical traps with mal/good code examples.",
        "when_to_use": "A failure mode is discovered that will recur; future agents must not repeat it.",
        "implementation_guide": [
            "`IAC_TRAPS.md` numbered sections: symptom, cause, fix",
            "Include minimal mal vs bien code snippets",
            "Document real-case origin (session, repo, date) for credibility",
            "Append-only; search before reporting 'no healthcheck' type false negatives",
        ],
        "related": ["protocol_writing", "session_audit"],
        "en": "Codified traps turn past failures into institutional knowledge.",
        "es": "Los traps codificados convierten fallos pasados en conocimiento institucional.",
    },
]


def list_patterns(domain: Optional[str] = None) -> list[dict]:
    """Return all patterns (4 tiers), optionally filtered by domain.

    Tier order: built-in → knowledge (committed) → workspace (ecosystem)
    → custom (personal, gitignored).

    Args:
        domain: 'coordination', 'identity', 'security', 'observability',
                'workflow', 'interface' or 'knowledge'. None returns all.
    """
    all_patterns = (
        PATTERNS                                    # tier 1: built-in
        + storage.load_knowledge_patterns()         # tier 2: committed community
        + storage.load_workspace_patterns()          # tier 2.5: ecosystem branch
        + storage.load_custom_patterns()             # tier 3: personal gitignored
    )
    if domain is None or domain == "all":
        return all_patterns
    return [p for p in all_patterns if p.get("domain") == domain]


def get_pattern(name: str) -> Optional[dict]:
    """Return a single pattern by name across all tiers, or None if not found."""
    for p in list_patterns():
        if p.get("name") == name:
            return p
    return None


def get_domains() -> list[str]:
    """Return the sorted list of distinct pattern domains (incl. all tiers)."""
    return sorted({p.get("domain") for p in list_patterns()})
